### ISSUE TITLE
Style svggradientbackgroundmaker

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#19]

**Comment by melanierichards** [comment]
Reopening for design / front-end review.

**Comment by ghost** [comment]
[slightly related]

> if `<path>` element of SVG has `fill-opacity` property set and the element is using a marker, the opacity would be inherited by marker, even if marker element is _not_ the child of path.

Given this code:

``` svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">

    <marker id="m1" style="overflow: visible; fill: #700;" orient="auto">
        <path style="fill-rule: evenodd; stroke: black; stroke-width: 1pt;" transform="matrix(0.8 0 0 0.8 5.70039 0.8)" d="M -2.5 -1 C -2.5 1.76 -4.74 4 -7.5 4 C -10.26 4 -12.5 1.76 -12.5 -1 C -12.5 -3.76 -10.26 -6 -7.5 -6 C -4.74 -6 -2.5 -3.76 -2.5 -1 Z" />
    </marker>

    <marker id="m2" style="overflow: visible; fill: #070;" orient="auto">
         <path style="fill-rule: evenodd; stroke: black; stroke-width: 1pt;" transform="scale(-0.8)" d="M 5.77 0 L -2.88 5 L -2.88 -5 L 5.77 0 Z" />
    </marker>

    <marker id="m3" style="overflow: visible; fill: #007;" orient="auto">
        <path style="fill-rule: evenodd; stroke: black; stroke-width: 1pt;" transform="scale(0.8)" d="M -5 -5 L -5 5 L 5 5 L 5 -5 L -5 -5 Z" />
    </marker>

    <path style="fill: none; fill-opacity: 0.75; fill-rule: evenodd; marker-end: url('#m1'); marker-mid: url('#m2'); marker-start: url('#m3'); stroke: red; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 4; stroke-opacity: 1; stroke-width: 2.5;" d="M 240 180 C 260 160 280 160 300 180 C 320 200 340 200 360 180"/>

</svg>
```

Result:

![ie-svg-bug](https://cloud.githubusercontent.com/assets/2031765/8247454/f51c494e-1659-11e5-9f1a-4ebd2530edfe.png)

Is this an undefined behavior in spec or a bug in IE10+ and Edge?

**Comment by melanierichards** [comment]
@molant do you know who the original author is on this one?

**Comment by molant** [comment]
No idea :(

-----Original Message-----

**Comment by ghost** [comment]
Actually this issue was reported on Connect quite a while back, but not sure if it is the violation of spec or undefined behavior: https://connect.microsoft.com/IE/feedback/details/772099/wrong-inheritance-with-svgs-fill-opacity. 
Would be really cool if we get a repository on GitHub (say MicrosoftEdge/SpecTests) where we can submit tests cases in an organized way, for instance; input and expected output in TODO folder (like `TODO/SVG/Inheritance/1/path-inheritance.[svg/png]`, `TODO/JavaScript/..` etc.). This will probably make it easier for the teams to move tests form TODO to DONE folder once the feature is implemented or the bug is fixed, so community can follow-up on their concerns. :)
I know you guys are very busy at the moment, but please consider this in future. With that said, thank you for bringing great new features to Edge. :+1:

**Comment by ststimac** [comment]
Closed. Duplicate of issue #161
