### ISSUE TITLE
Add aria live regions to Fish tank

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#309]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/fishietank/

The script constantly updates the title attribute of the canvas. Need to test and look into adding Aria live region so that that update is reflected to the screen reader (preferably using polite so it doesn't spam the user

**Comment by alrra** [comment]
>  look into adding Aria live region so that that update is reflected to the screen reader (preferably using polite so it doesn't spam the user

From https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

> Normally, only aria-live="polite" is used. Any region which receives updates that are important for the user to receive, **but not so rapid as to be annoying, should receive this attribute**. The screen reader will speak changes whenever the user is idle.

@dstorey Even using `aria-live="polite"`, because the updates are sometimes so [frequent](https://github.com/MicrosoftEdge/Demos/blob/7c0cb459588d245de9de240b7abcd164388308a2/fishietank/scripts/fpsometer.js#L105), `ChromeVox` for example, will just get to read part of the text, the end result being: _"Demo is running, Demo is running, Demo is running..."._

**Comment by dstorey** [comment]
@alrra the main point of this demo is how many FPS you get, so we'll need some way to update the screen reader about that. The good thing about "polite" is that it shouldn't update when the screen reader is otherwise speaking out another part of the page. If the FPS is fairly constant then the text won't update often and won't be too bad, but if it is flicking up and down a lot it could be pretty bad. I'm not sure if we can do something where it notifies the screen reader of the change less often.

Either way we probably only want the xx fps part to update rather than reading out the entire demo is running at xx fps.
