### ISSUE TITLE
[Variable Fonts] Interactive Examples?

### ISSUE THREAD

**Issue by Martin-Pitt** [MicrosoftEdge/Demos-old#407]
Taking a leaf from [explorabl.es](http://explorabl.es/):

I think the test drive will benefit a lot from being able to literally test drive variable fonts by putting the reader in the driver seat: Sprinkle a few `<input type="range">` sliders around to empower readers to become engaged with this new rich typography.

Reactive Animations provide a learning that is a powerful way to understand the space of possibilities by testing their own understanding, from playing outside of their usual expectations (font-weights that sit in-between, they'd think "would 334 work? hm… OH! AWESOME") to seeing how dynamic input of the digital medium could lead to richer communication.

**Comment by gregwhitworth** [comment]
Hey @Martin-Pitt - thanks for taking the time to post this. I don't disagree with you that it is a compelling way to "empower readers", that said (and I apologize if I'm mis-characterizing your intent) but within this guide nothing is "sprinkled" in but is given a lot of time and thought about how it is placed and how it effects the overall experience of the piece. We really wanted to marry long form journalism with an engaging experience about a cool technology.  As such, it would take more time than we can currently devote to adding in range inputs but will keep the suggestion for future endeavors. However, so that the users can play with the code - we put them into a collection on [Codepen Collection](https://codepen.io/collection/nryNjW/#). Again, thank you so much for taking the time to reach out regarding this - have a good day!
